---
# tasks file for aws-efs
- name: Ensure 'git', 'make', 'binutils' are installed
  ansible.builtin.apt:
    name: "{{ aws_efs_prerequisites }}"
    state: present
    update_cache: true

- name: Git Clone EFS Utils
  ansible.builtin.git:
    repo: "{{ aws_efs_github_url }}"
    dest: /var/tmp/efs
    version: "{{ aws_efs_version }}"

- name: Build EFS Utils
  ansible.builtin.command: bash build-deb.sh
  args:
    chdir: /var/tmp/efs
  register: efs_build
  changed_when: efs_build.rc != 0


- name: Get all scripts in /usr/local/bin/aws-scripts-mon/
  ansible.builtin.find:
    paths: /var/tmp/efs/build/
    file_type: file
    use_regex: true
    patterns:
      - "^amazon-efs-utils*deb$"
  register: aws_efs_build_packages

- name: Install build aws efs packages
  ansible.builtin.apt:
    deb: "/var/tmp/efs/build/{{ item }}"
    state: present
  loop: "{{ aws_efs_build_packages }}"

- name: Cleanup
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/tmp/efs/
